[package]
name = "minnie"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]

[dependencies]
unicode-xid = "0.1.0"
rustyline = { git = "https://github.com/kkawakam/rustyline" }

[dependencies.nom]
version = "^3.1"
features = ["verbose-errors"]
